spring.application.name=OSApplication
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/alml_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=alml
spring.datasource.password=2diSenai
spring.jpa.show-sql=True

